### ISSUE TITLE
Some help clarifications 

### ISSUE THREAD

**Issue by PsychotropicDog** [nsensfel/relabsd#2]
Ubuntu MATE 17.10
Instead of /dev/input
find the device in
/dev/input/by-id/
usb-3Dconnexion_SpaceMouse_Pro-event-mouse
so can be called from that location with:
sudo ./relabsd /dev/input/by-id/usb-3Dconnexion_SpaceMouse_Pro-event-mouse ../conf/space_navigator.conf

In this distro the device will also control the mouse pointer, which may not be desirable.
So I usually disable the device like so:
xinput # to get the <id>
xinput --disable <id>
then start relabsd
then disable the relabsd one through xinput.

Now the device works as desired. Works great in NeonXSZ.

**Comment by nsensfel** [comment]
Thanks.
I've added a link [from the wiki](https://github.com/nsensfel/relabsd/wiki/Creating-a-virtual-device) to this page so that people get an alternative way to set things up.
